const abi_iequilibria_pendle_booster_mainchain = [
    "function DENOMINATOR() view returns (uint256)",
    "function MaxFees() view returns (uint256)",
    "function addPool(address _market, address _token, address _rewardPool) external",
    "function addPoolBeacon(address _market) external",
    "function contributor() view returns (address)",
    "function deposit(uint256 _pid, uint256 _amount, bool _stake) external",
    "function depositAll(uint256 _pid, bool _stake) external",
    "function ePendleIncentive() view returns (uint256)",
    "function ePendleRewardPool() view returns (address)",
    "function ePendleRewardReceiver() view returns (address)",
    "function earmarkIncentive() view returns (uint256)",
    "function earmarkOnOperation() view returns (bool)",
    "function earmarkRewards(uint256 _pid) external",
    "function earmarkRewardsManually(uint256 _pid, uint256[] memory _amounts) external",
    "function eqb() view returns (address)",
    "function eqbConfig() view returns (address)",
    "function eqbMinter() view returns (address)",
    "function farmEqbShare() view returns (uint256)",
    "function initialize() external",
    "function isShutdown() view returns (bool)",
    "function owner() view returns (address)",
    "function pendle() view returns (address)",
    "function pendleProxy() view returns (address)",
    "function platformFee() view returns (uint256)",
    "function poolInfo(uint256) view returns (address market, address token, address rewardPool, bool shutdown)",
    "function poolLength() view returns (uint256)",
    "function renounceOwnership() external",
    "function rewardClaimed(uint256 _pid, address _account, address _token, uint256 _amount) external",
    "function setContributor(address _contributor) external",
    "function setEarmarkOnOperation(bool _earmarkOnOperation) external",
    "function setEqbConfig(address _eqbConfig) external",
    "function setFarmEqbShare(uint256 _farmEqbShare) external",
    "function setFees(uint256 _vlEqbIncentive, uint256 _ePendleIncentive, uint256 _platformFee, uint256 _earmarkIncentive) external",
    "function setParams(address _pendle, address _pendleProxy, address _eqbMinter, address _eqb, address _xEqb, address _vlEqb, address _ePendleRewardReceiver, address _ePendleRewardPool, address _treasury) external",
    "function setTeamEqbShare(uint256 _teamEqbShare) external",
    "function setTreasury(address _treasury) external",
    "function setVlEqb(address _vlEqb) external",
    "function shutdownPool(uint256 _pid) external",
    "function shutdownSystem() external",
    "function teamEqbShare() view returns (uint256)",
    "function transferOwnership(address newOwner) external",
    "function treasury() view returns (address)",
    "function vlEqb() view returns (address)",
    "function vlEqbIncentive() view returns (uint256)",
    "function withdraw(uint256 _pid, uint256 _amount) external",
    "function withdrawAll(uint256 _pid) external",
    "function xEqb() view returns (address)"
];
